import os


SSH_GATEWAY_HOST = os.environ['SSH_GATEWAY_HOST']
SSH_GATEWAY_PORT = int(os.environ['SSH_GATEWAY_PORT'])
SSH_GATEWAY_USER = os.environ['SSH_GATEWAY_USER']
SSH_GATEWAY_PKEY = os.environ['SSH_GATEWAY_PKEY']
REMOTE_BIND_HOST = os.environ['REMOTE_BIND_HOST']
REMOTE_BIND_PORT = int(os.environ['REMOTE_BIND_PORT'])
REDIS_AUTH = os.environ['REDIS_AUTH']
